version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: email_app_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: email_app
    volumes:
      - mongodb_data:/data/db
    networks:
      - email_app_network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: email_app_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-super-secret-key-change-in-production
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/email_app?authSource=admin
      - ALLOWED_ORIGINS=http://localhost:3000,http://frontend:3000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - email_app_network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: email_app_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - email_app_network

volumes:
  mongodb_data:

networks:
  email_app_network:
    driver: bridge